# Generated by Django 4.0 on 2022-09-19 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BillingAddtress',
            new_name='BillingAddress',
        ),
    ]
